### PR TITLE
Upgrade kubectl to v1.14.3

### PR DESCRIPTION
**Pull request by dadjeibaah**
Signed-off-by: Dennis Adjei-Baah <dennis@buoyant.io>

### CODE REVIEW

**Review by klingerf — APPROVED** [review]
⭐️ Nice, works for me!

**Review by siggy — APPROVED** [review]
looks good! i just enabled automated builds for https://hub.docker.com/r/buoyantio/kubectl (TIL you can now convert a normal Docker Hub repo into an Automated Build repo!)

merging master should trigger a new build of `latest`, and then if you create a `v1.14.3` tag, it should also create an analogous docker image.

```bash
$docker build -t buoyantio/kubectl:latest .
...
$ docker run buoyantio/kubectl:latest version --short --client
Client Version: v1.14.3
```

**Comment by dadjeibaah** [comment]
@siggy woah, that's some fancy stuff. Do I still have to create a docker tag locally and then push? I tried looking through the UI in DockerHub and I don't see where I can create a tag to trigger an automated build.

**Comment by siggy** [comment]
@dadjeibaah You shouldn't have to create a Docker tag, instead create a git tag (either locally or via a Github Release). That should kick off the Automated Build on Docker Hub.

**Pull request merged**
